### ISSUE TITLE
Build issue on node version > 10

### ISSUE THREAD

**Issue by adrianbrowning** [ourarash/log-with-statusbar#2]
Looks like there is an issue with `get-cursor-position` package and causes the build to fail.
Using the original package instead seems to fix this issue.
```node_modules/.pnpm/github.com/ourarash/get-cursor-position@cbdc2edaa293d256bda4b298f7bb52f0a920ee55/node_modules/get-cursor-position: Running install script, failed in 2.1s
.../node_modules/get-cursor-position install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@7.1.2
│ gyp info using node@12.18.3 | darwin | x64
│ gyp info find Python using Python version 3.9.0 found at "/usr/local/opt/python@3.9/bin/python3.9"
│ gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
│ gyp info spawn args [
│ gyp info spawn args   '/Users/adrianbrowning/.nvm/versions/node/v12.18.3/pnpm-global/4/node_modules/.pnpm/pnpm@5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/adrianbrowning/Documents/code/node.js/magic-metrics-tool/node_modules/.pnpm/github.com/ourarash/get-cursor-position@cbdc2edaa293d256bda4b298f7bb52f0a920ee55/node_modules/get-cursor-position/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/adrianbrowning/.nvm/versions/node/v12.18.3/pnpm-global/4/node_modules/.pnpm/pnpm@5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/adrianbrowning/Library/Caches/node-gyp/12.18.3',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/adrianbrowning/.nvm/versions/node/v12.18.3/pnpm-global/4/node_modules/.pnpm/pnpm@5.16.0/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/adrianbrowning/Documents/code/node.js/magic-metrics-tool/node_modules/.pnpm/github.com/ourarash/get-cursor-position@cbdc2edaa293d256bda4b298f7bb52f0a920ee55/node_modules/get-cursor-position',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│   CXX(target) Release/obj.target/pos/src/pos.o
│ ../src/pos.cc:256:22: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
│     pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
│                      ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3030:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
│   static V8_DEPRECATED(
│          ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
│   declarator __attribute__((deprecated(message)))
│                             ^
│ ../src/pos.cc:256:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
│     pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
│          ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
│   V8_DEPRECATED("Use maybe version",
│   ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
│   declarator __attribute__((deprecated(message)))
│                             ^
│ ../src/pos.cc:257:22: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
│     pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
│                      ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3030:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
│   static V8_DEPRECATED(
│          ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
│   declarator __attribute__((deprecated(message)))
│                             ^
│ ../src/pos.cc:257:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
│     pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
│          ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
│   V8_DEPRECATED("Use maybe version",
│   ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
│   declarator __attribute__((deprecated(message)))
│                             ^
│ ../src/pos.cc:263:24: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
│   exports->Set(String::NewFromUtf8(isolate, "sync"),
│                        ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3030:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
│   static V8_DEPRECATED(
│          ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
│   declarator __attribute__((deprecated(message)))
│                             ^
│ ../src/pos.cc:264:59: error: too few arguments to function call, single argument 'context' was not specified
│       FunctionTemplate::New(isolate, Method)->GetFunction());
│       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8.h:6126:3: note: 'GetFunction' declared here
│   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
│   ^
│ /Users/adrianbrowning/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
│ #define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
│                               ^
│ 5 warnings and 1 error generated.
│ make: *** [Release/obj.target/pos/src/pos.o] Error 1
│ gyp ERR! build error
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/Users/adrianbrowning/.nvm/versions/node/v12.18.3/pnpm-global/4/node_modules/.pnpm/pnpm@5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/lib/build.js:194:23)
│ gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
│ gyp ERR! System Darwin 19.6.0
│ gyp ERR! command "/Users/adrianbrowning/.nvm/versions/node/v12.18.3/bin/node" "/Users/adrianbrowning/.nvm/versions/node/v12.18.3/pnpm-global/4/node_modules/.pnpm/pnpm@5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /Users/adrianbrowning/Documents/code/node.js/magic-metrics-tool/node_modules/.pnpm/github.com/ourarash/get-cursor-position@cbdc2edaa293d256bda4b298f7bb52f0a920ee55/node_modules/get-cursor-position
│ gyp ERR! node -v v12.18.3
│ gyp ERR! node-gyp -v v7.1.2
│ gyp ERR! not ok
└─ Failed in 2.1s```

**Comment by ourarash** [comment]
I updated the package. Please try downloading from npm again. However, it will only work if you have a system that has `bash`. I have tested it on Linux and Mac, but not Windows.
